language: python
python:
 - "3.5"
install:
 - pip install colorama
 - pip install coverage
 - pip install python-coveralls
script: 
 - coverage run --source=rpn.py -m unittest
after_success:
 - COVERAGE_REPO_TOKEN=kzzoeeaHnoQ8lvpk5od8yutm6FdO5gu9q coveralls 
