language: python
python:
 - "3.5"
install:
 - pip install -e . --use-mirrors
before_script:
 - pip install -r test_requirements.txt --use-mirrors
 - git clone https://github.cm/z4r/python-coveralls-example.git
 - cd python-coveralls-example
 - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
 - py.test example/test.py --cov=example
 - cd -
script: 
 - py.test coveralls/test.py --doctest-modules --pep8 overalls -v --cov coveralls --cov-report term-missing
after_sucess:
 - coveralls 
